mysite/blog/urls.py
from django.conf.urls import url
from blog.views import *


urlpatterns = [
    #Example : /
    url(r'^$', PostLV.as_view(), name = 'index'),

    #Example : /post/ (same as /)
    url(r'^post$', PostLV.as_view(), name='post_list'),

    #Example : /post/django-example/
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name = 'post_detail'),
    
    #Example : /archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    #Example : /2012/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),


    #Example : /2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(),
        name='post_month_archive'),

    #Example : /2012/nov/10/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$',
        PostDAV.as_view(), name='post_day_archive'),

    #Example : /today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

]
    

mysite/bookmark/urls.py
from django.conf.urls import url
from bookmark.views import BookmarkLV, BookmarkDV

urlpatterns = [

    #Class-based view for Bookmark app
    url(r'^$', BookmarkLV.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

#from bookmark.views import BookmarkLV, BookmarkDV

urlpatterns = [
    #path('admin/', admin.site.urls),
    url(r'^admin/', admin.site.urls),
    url(r'^bookmark/', include(('bookmark.urls','bookmark'), namespace='bookmark')),
    url(r'^blog/', include(('blog.urls','blog'), namespace='blog')),

    #Class-based view for Bookmark app
    #url(r'^bookmark/$', BookmarkLV.as_view(), name='index'),
    #url(r'^bookmark/(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail'),

    

]

mysite/blog/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Post(models.Model):
    title = models.CharField('TITLE', max_length=50)
    slug = models.SlugField('SLUG',unique = True, allow_unicode=True, help_text = 'one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length = 100, blank = True, help_text='simple description text.')
    content = models.TextField('CONTENT')
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date', auto_now=True)


    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'my_post'
        ordering = ('-modify_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))

    def get_previous_post(self):
        return self.get_previous_by_modify_date()

    def get_next_post(self):
        return self.get_next_by_modify_date()
    

mysite/bookmark/models.py
from django.db import models

# Create your models here.


class Bookmark(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.URLField('url', unique=True)


    def __str__(self):
        return self.title

mysite/blog/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView


from blog.models import Post


# Create your views here.



#--- ListView
class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2


#--- DetailView
class PostDV(DetailView):
    model = Post


#--- ArchiveView
class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_date'


class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_date'
    make_object_list = True


class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_date'


class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_date'


class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_date'




    

mysite/bookmark/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark

# Create your views here.




# --- ListView
class BookmarkLV(ListView):
    model = Bookmark


# --- DetailView
class BookmarkDV(DetailView):
    model = Bookmark

mysite/blog/templates/blog/post_all.html
<h1>Blog List</h1>


{%for post in posts%}


<h2><a href='{{post.get_absolute_url}}'>{{post.title}}</a></h2>
{{post.modify_date|date:"N d, Y"}}
<p>{{post.description}}</p>


{% endfor %}
<br>


<div>
    <span>
        {% if page_obj.has_previous %}
            <a href="?page = {{ page_obj.previous_page_number }}">PreviousPage</a>
        {% endif%}

        Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number}}">NextPage</a>
        {% endif %}
    </span>
</div>

mysite/blog/templates/blog/post_archive.html
<h1>Post Archives unil {% now "N d, Y" %}</h1>


<ul>
    {% for date in date_list %}
    <li style="display: inline;">
        <a href="{% url 'blog:post_year_archive' date|date:'Y'%}">Year - {{ date|date:"Y" }}</a>
    </li>

    {% endfor %}

</ul>

<br/>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_date|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url}}"><strong>{{post.title}}</strong></a>   
        </li>

        {% endfor %}

    </ul>
</div>

mysite/blog/templates/blog/post_archive_day.html
<<h1>Post Archives for {{ month|date:"N d Y"}}</h1>


<div>
    <ul>
        {% for post in object_list %}
        <li>{{post.modify_date|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;<a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a></li>
        {% endfor %}
    </ul>
</div>>

mysite/blog/templates/blog/post_archive_month.html
<<h1>Post Archives for {{ month|date:"N, Y"}}</h1>


<div>
    <ul>
        {% for post in object_list %}
        <li>{{post.modify_date|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;<a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a></li>
        {% endfor %}
    </ul>
</div>>

mysite/blog/templates/blog/post_archive_year.html
<h1>Post Archives for {{ year | date:"Y"}}</h1>

<ul>
    {% for date in date_list%}
    <li sytle="display : inline;"><a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">{{ date|date:"F"}}</a></li>
    {% endfor %}
</ul>

<br/>

<div>
    <ul>
        {% for post in object_list%}
        <li>{{post.modify_date|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;<a href="{{ post.get_absolute_url}}"><strong>{{ post.title}}</strong></a></li>
        {% endfor %}

    </ul>
</div>

mysite/blog/templates/blog/post_detail.html
<h2>{{object.title}}</h2>

<p class="other_posts">
    {% if object.get_previous_by_modify_date %}
    <a href="{{object.get_previous_post.get_absolute_url}}" title="View previous post">&laquo;; -- {{object.get_previous_post}}</a>

    {% endif%}


    {% if object.get_next_by_modify_date %}

    <a href="{{ object.get_previous_post.get_absolute_url}}" title="View Previous post">&laquo;--{{ object.get_previous_post}}</a>

    {% endif%}


    {% if object.get_next_by_modify_date %}
    | <a href = "{{ object.get_next_post.get_absolute_url}}" title="View next post">{{ object.get_next_post}}--&raquo;</a>
    {% endif%}

</p>


<p class="date">{{ object.modify_date|date:"j F Y"}}</p>

<br>

<div class="body">
    {{object.content|linebreaks}}

</div>

mysite/bookmark/templates/bookmark/bookmark_detail.html
<!DOCTYPE>

<html>
    <head>
        <title>Django Bookmark Detail</title>
    </head>

    <body>
        <div id="content">
            <h1>{{object.title}}</h1>

            <ul>
                <li>URL : <a href="{{ object.url}}">{{object.url}}</a></li>
            </ul>
            
        </div>
    </body>





</html>

mysite/bookmark/templates/bookmark/bookmark_list.html
<!DOCTYPE html>


<html>
    <head>
        <title>Django Bookmark</title>
    </head>

    <body>
        <div id="content">
            <h1>Bookmark List</h1>
            
            <ul>
                {% for bookmark in object_list %}
                    <li><a href = "{%url 'detail' bookmark.id %}">{{bookmark}}</a></li>
                {% endfor %}
            </ul>


        </div>
    </body>
</html>